### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by rrosson** [oh-my-fish/plugin-sublime#6]
Sublime starts but it does not open the file or directing in the application.No errors are printed in the terminal.

**Comment by bpinto** [comment]
Could you check this @bobthecow ? I believe you use sublime.

**Comment by bobthecow** [comment]
It works just fine for me (OS X 10.10, 10.11 / Sublime Text 3). Can you give us more details about your setup?

**Comment by nemoDreamer** [comment]
I have a strange case:
I used to have my own `subl` symlink in `/usr/local/bin/`. I recently updated to OS X 10.11, and thought "hm, let me see if `omf` has a sublime package".

I use Sublime a lot as my git commit message editor via my config:

``` bash
set -g -x EDITOR "subl -w"
set -g -x VISUAL "subl -w"
```

After removing my symink, and installing this plugin, I can use `subl [dir | file]` etc just fine, but get the following when I run `git commit` or commit via `tig`:

```
subl -w: subl: command not found
error: There was a problem with the editor 'subl -w'.
Please supply the message using either -m or -F option.
```

Is the function not globally available? It's available in the same session I use to run the git command... :panda_face:

**Comment by rrosson** [comment]
Sorry for wasting everyones time on this. I did a little more digging and this shows up when you are trying to do open a file from within tmux. The fix was to change the syntax to be fish friendly in my .tmux.conf. The commented out line is what I used to have.
<code>
#set -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL -l"

set -g default-command "which reattach-to-user-namespace > /dev/null; and reattach-to-user-namespace -l $SHELL; or $SHELL -l"
</code>

This issue can now be closed for me.

**Comment by scorphus** [comment]
Please, close the issue, @rrosson
